"""create trend

Revision ID: 03b176d60e79
Revises: fa0c9e746e4e
Create Date: 2021-06-30 16:13:03.557590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03b176d60e79'
down_revision = 'fa0c9e746e4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
