"""create api_cache

Revision ID: 3f19be4cfd7a
Revises: 9bfd8378257e
Create Date: 2021-06-27 13:44:16.769448

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3f19be4cfd7a'
down_revision = '9bfd8378257e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_cache',
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp'), nullable=False),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp on update current_timestamp'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('celeb_name', sa.String(length=100), nullable=False),
    sa.Column('yt_cache', sa.JSON(), nullable=True),
    sa.Column('tw_cache', sa.JSON(), nullable=True),
    sa.Column('nw_cache', sa.JSON(), nullable=True),
    sa.Column('wk_cache', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('celeb_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('api_cache')
    # ### end Alembic commands ###
