"""fix nickname

Revision ID: 66678b0b8ccc
Revises: f883543f1d9f
Create Date: 2021-07-01 22:40:24.417826

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '66678b0b8ccc'
down_revision = 'f883543f1d9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('nickname', table_name='nickname')
    op.drop_column('nickname', 'nickname')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nickname', sa.Column('nickname', mysql.VARCHAR(collation='utf8_unicode_ci', length=50), nullable=False))
    op.create_index('nickname', 'nickname', ['nickname'], unique=False)
    # ### end Alembic commands ###
