"""create twitter

Revision ID: 99ab38ec8caa
Revises: b454a02cfad0
Create Date: 2021-06-23 17:47:59.150480

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '99ab38ec8caa'
down_revision = 'b454a02cfad0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('twitter',
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp'), nullable=False),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp on update current_timestamp'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('whose', sa.String(length=20), nullable=False),
    sa.Column('nankome', sa.Integer(), nullable=False),
    sa.Column('api_key', sa.String(length=50), nullable=False),
    sa.Column('api_key_secret', sa.String(length=50), nullable=False),
    sa.Column('access_token', sa.String(length=50), nullable=False),
    sa.Column('access_token_secret', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('twitter')
    # ### end Alembic commands ###
