"""create oshido, youtube, twitter, news

Revision ID: 9bfd8378257e
Revises: 
Create Date: 2021-06-24 19:22:54.400361

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9bfd8378257e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news',
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp'), nullable=False),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp on update current_timestamp'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('whose', sa.String(length=20), nullable=False),
    sa.Column('nankome', sa.Integer(), nullable=False),
    sa.Column('api_key', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_key'),
    sa.UniqueConstraint('whose', 'nankome', name='unique_whose_nankome')
    )
    op.create_table('oshido',
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp'), nullable=False),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp on update current_timestamp'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(length=50), nullable=False),
    sa.Column('celeb_name', sa.String(length=100), nullable=False),
    sa.Column('oshido', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uid', 'celeb_name', name='unique_uid_celeb_name')
    )
    op.create_table('twitter',
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp'), nullable=False),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp on update current_timestamp'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('whose', sa.String(length=20), nullable=False),
    sa.Column('nankome', sa.Integer(), nullable=False),
    sa.Column('api_key', sa.String(length=50), nullable=False),
    sa.Column('api_key_secret', sa.String(length=50), nullable=False),
    sa.Column('access_token', sa.String(length=50), nullable=False),
    sa.Column('access_token_secret', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('access_token'),
    sa.UniqueConstraint('access_token_secret'),
    sa.UniqueConstraint('whose', 'nankome', name='unique_whose_nankome')
    )
    op.create_table('youtube',
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp'), nullable=False),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp on update current_timestamp'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('whose', sa.String(length=20), nullable=False),
    sa.Column('nankome', sa.Integer(), nullable=False),
    sa.Column('api_key', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_key'),
    sa.UniqueConstraint('whose', 'nankome', name='unique_whose_nankome')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('youtube')
    op.drop_table('twitter')
    op.drop_table('oshido')
    op.drop_table('news')
    # ### end Alembic commands ###
